apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-fdbz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-fdbz
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-fdbz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-fdbz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-fdbz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-bnre-tenant/appstudio/dc-metro-map-fdbz@sha256:f90c4a8b7e6c0d503b72d7ee09b1f5eef90c524f4005251c29e55723b54f7107
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
